stages:
  - build
  - test
  - deploy

build-job:
  tags:
    - atria
  stage: build
  script:
    - echo build number is $CI_BUILD_REF
    - cd report_accumulator
    - ./gradlew build deployReports -Dorg.gradle.project.buildNumber=$CI_BUILD_REF
  only:
    - master

