stages:
  - build
  - test
  - deploy

before-script:

  - eval $(ssh-agent -s)
  - ssh-add <(echo "$REPORTS_SSH_KEY")

build-job:
  tags:
    - atria
  stage: build
  script:
    - echo build number is $CI_BUILD_REF
    - export BUILD_LABEL="`date -I` $CI_BUILD_REF"
    - cd report_accumulator
    - ./gradlew build reports
    - cd ../demo
    - ./gradlew deployReports -Dorg.gradle.project.buildNumber="$BUILD_LABEL"
  only:
    - master

