stages:
  - build
  - test
  - deploy

build-job:
  tags:
    - atria
  stage: build
  script:
    - pwd
    - cd report-accumulator
    - pwd
    - ./gradlew build
    - mkdir -p /home/zeil/public_html/gitlab/report-accumulator
    - /bin/cp -arf build/reports /home/zeil/public_html/gitlab/report-accumulator
  only:
    - master

