stages:
  - build
  - test
  - deploy


build-job:
  tags:
    - ssh-3208
  stage: build
  script:
    - echo build number is $CI_BUILD_REF
    - eval $(ssh-agent -s)
    - ssh-add <(echo "$REPORTS_SSH_KEY")
    - export BUILD_LABEL="`date -Idate` $CI_BUILD_REF"
    - cd report_accumulator
    - ./gradlew build reports
    - cd ../demo
    - ./gradlew deployReports -Dorg.gradle.project.buildNumber="$BUILD_LABEL"
  only:
    - master

