stages:
  - build
  - test
  - deploy

build-job:
  tags:
    - atria
  stage: build
  script:
    - echo build number is $CI_BUILD_ID
    - cd report_accumulator
    - ./gradlew build deployReports -DBuild_Number=$CI_BUILD_ID
  only:
    - master

