stages:
  - build
  - test
  - deploy

build-job:
  tags:
    - atria
  stage: build
  script:
    - echo build number is $CI_BUILD_REF
    - BUILDID=`date -I` $CI_BUILD_REF
    - cd demo
    - ./gradlew build deployReports -Dorg.gradle.project.buildNumber=$BUILDID
  only:
    - master

